apiVersion: v1
name: containiq
version: v0.1.0
description: Monitor and debug your kubernetes cluster
keywords:
  - containiq
  - kubernetes
  - monitoring
  - debugging
home: https://containiq.com
sources:
  - https://github.com/containiq/containiq
maintainers: # (optional)
  - name: Matthew Lenhard
    email: matt@containiq.com

