#run tests when push to repo
name: Docker Image CI
on: [push]
jobs:
  test:
    name: integration test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
          chmod +x ./kind
          mv ./kind ~/.
      - name: create kind cluster
        run: kind create cluster
      - name: run integration test
        run: go test ./test/